export const states =  [
    {name: "Acre", region: "AC"},
    {name: "Alagoas", region: "AL"},
    {name: "Amapá", region: "AP"},
    {name: "Amazonas", region: "AM"},
    {name: "Bahia", region: "BA"},
    {name: "Ceará", region: "CE"},
    {name: "Distrito Federal", region: "DF"},
    {name: "Espírito Santo", region: "ES"},
    {name: "Goiás", region: "GO"},
    {name: "Maranhão", region: "MA"},
    {name: "Mato Grosso", region: "MT"},
    {name: "Mato Grosso do Sul", region: "MS"},
    {name: "Minas Gerais", region: "MG"},
    {name: "Pará", region: "PA"},
    {name: "Paraíba", region: "PB"},
    {name: "Paraná", region: "PR"},
    {name: "Pernambuco", region: "PE"},
    {name: "Piauí", region: "PI"},
    {name: "Rio de Janeiro", region: "RJ"},
    {name: "Rio Grande do Norte", region: "RN"},
    {name: "Rio Grande do Sul", region: "RS"},
    {name: "Rondônia", region: "RO"},
    {name: "Roraima", region: "RR"},
    {name: "Santa Catarina", region: "SC"},
    {name: "São Paulo", region: "SP"},
    {name: "Sergipe", region: "SE"},
    {name: "Tocantins", region: "TO"}
  ]